### ISSUE TITLE
WTB IGNORED_STRUCT_ARG

### ISSUE THREAD

**Issue by anporumb** [Azure/umock-c#110]
There is an `IGNORED_PTR_ARG` (nice) and `IGNORED_NUM_ARG`.

However, if there's a function that takes as parameter a struct (not a pointer to struct, but the struct itself) then umock_c does not offer a convenient way of saying "ignore this parameter that is a struct".

Random thoughts: `{0}` is always a valid initializer for a struct. Maybe a IGNORED_STRUCT_ARG(TYPE) would be needed to help the PP (but TYPE is already known, so magic might be needed).

Best Regards,
Andrei Porumb

**Comment by dcristoloveanu** [comment]
Done with #154
