### ISSUE TITLE
Access violation using with mstest

### ISSUE THREAD

**Issue by acsvln** [Azure/umock-c#118]
I am trying to use umock-c with mstest build-in visual studio 2017.
Here my code draft:
```
#define ENABLE_MOCKS

#include <umock_c/umock_c.h>

...

 MOCKABLE_FUNCTION(, int, test_dependency_1_arg, int, arg1);

...

  TEST_METHOD(TestTest)
  {

      // arrange
    STRICT_EXPECTED_CALL(test_dependency_1_arg(42))
        .SetReturn(44)
        .IgnoreAllArguments();

   // test_dependency_1_arg(42);

    //Assert::AreEqual(umock_c_get_expected_calls(), umock_c_get_actual_calls());

}
...
```
After running TestTest case i got message exception with code C0000005 in `STRICT_EXPECTED_CALL` line, or in `test_dependency_1_arg(42)` line (if comment `STRICT_EXPECTED_CALL ` line).
Why?

**Comment by dcristoloveanu** [comment]
I know this is after soooooooo much time. I got now some time to looks at some of the older issues in here. I suspect that the issue could have been that umock_init was not called, but I cannot tell for sure.

I suspect that this being such an old issue, it probably does not affect you anymore. If it somehow does I'll try reproing it and looking into it.

Thanks,
/Dan

**Comment by dcristoloveanu** [comment]
I'll take it this is not an issue anymore, please do reopen if you are still facing it.
