### ISSUE TITLE
WTB MOCKABLE_FUNCTION_RETURNS

### ISSUE THREAD

**Issue by anporumb** [Azure/umock-c#30]
At the moment there's no way to specify in the header "what is the fail/success return value" for a MOCKABLE_FUNCTION.

It can be done in the unittests by means of REGISTER_GLOBAL_MOCK_RETURNS.

And for every header, every time, in every unittest that so happens to #include header, REGISTER_GLOBAL_MOCK_RETURNS needs to be defined.

The effects of REGISTER_GLOBAL_MOCK_RETURNS should be uniquely define-able in the header, overwritable in unittests (should the writer of the unittests so need it).

Best Regards,
Andrei Porumb

**Comment by dcristoloveanu** [comment]
This is a duplicate of  #26
